### 음식점 ID
@id = 1


### 음식점 생성 - 원할머니 보쌈
POST http://localhost:8080/restaurants
Content-Type: application/json

{
  "restaurantName": "원할머니보쌈",
  "description": "세상에서 가장 쫄깃하고 맛있는 보쌈집"
}

### 음식점 생성 - 스시앤스시
POST http://localhost:8080/restaurants
Content-Type: application/json

{
  "restaurantName": "스시앤스시",
  "description": "연어가 입안에서 요동치는 맛스시"
}


### 음식점 생성 - 돼지구이
POST http://localhost:8080/restaurants
Content-Type: application/json

{
  "restaurantName": "돼지구이",
  "description": "돼지고기가 일품인 고깃집"
}


### 전체 음식점 전체 목록 조회
GET http://localhost:8080/restaurants?page=1


### 특정 음식점 목록 조회
GET http://localhost:8080/restaurants/{{id}}


### 특정 음식점 수정
PUT http://localhost:8080/restaurants/{{id}}
Content-Type: application/json

{
  "restaurantName": "원할머니 족발",
  "description": "세상에서 가장 쫄깃하고 맛있는 족발집"
}


### 특정 음식점 삭제
DELETE http://localhost:8080/restaurants/{{id}}