### 회원가입
POST http://localhost:8080/users
Content-Type: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

{
  "accountId": "supplier0",
  "password": "Supplier0!",
  "name": "판매자",
  "email": "supplier@gmail.com",
  "userType" : "SUPPLIER"

}


### 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "accountId": "supplier0",
  "password": "Supplier0!"
}

> {%
    client.log(response.headers.valueOf("Authorization"));
    client.log(response.headers.valueOf("RefreshToken"));
    client.global.set("accessToken", response.headers.valueOf("Authorization"));
    client.global.set("refreshToken", response.headers.valueOf("RefreshToken"));
%}


### 로그아웃
POST http://localhost:8080/users/logout
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

> {%
    client.global.clear("accessToken");
    client.global.clear("refreshToken");
%}


### 회원 프로필 조회
GET http://localhost:8080/users
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}



### 회원 프로필 수정
PUT http://localhost:8080/users
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "name": "판매자업데이트",
  "intro": "음식으로 장난 안치는 판매자입니다.",
  "password": "Supplier0!",
  "newPassword": "Supplier1!"
}
