### 회원가입
POST http://localhost:8080/users
Content-Type: application/json
Cookie: accessToken={{accessToken}}; refreshToken={{refreshToken}}

{
  "accountId": "consumer0",
  "password": "Consumer0!",
  "name": "구매자",
  "email": "consumer@gmail.com",
  "userType" : "CONSUMER"

}


### 로그인
POST http://localhost:8080/users/login
Content-Type: application/json

{
  "accountId": "consumer0",
  "password": "Consumer0!"
}

> {%
    client.global.set("accessToken", response.headers.valueOf("Authorization"));
    client.global.set("refreshToken", response.headers.valueOf("RefreshToken"));
%}


### 로그아웃
POST http://localhost:8080/users/logout
Content-Type: application/json
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

> {%
    client.global.clear("accessToken");
    client.global.clear("refreshToken");
%}


### 회원 프로필 조회
GET http://localhost:8080/users
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}



### 회원 프로필 수정
PUT http://localhost:8080/users
accessToken: {{accessToken}}
refreshToken: {{refreshToken}}

{
  "name": "구매자업데이트",
  "intro": "보쌈에 진심인 구매자 박성균입니다.",
  "password": "Consumer0!",
  "newPassword": "Consumer1!"
}
